//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace WcfContract.Wcf
{
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class WcfConfigurationResource
    {

        private static ResourceManager resourceMan;

        private static CultureInfo resourceCulture;

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WcfConfigurationResource()
        {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    ResourceManager temp = new ResourceManager("Contract.Wcf.WcfConfigurationResource", typeof(WcfConfigurationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 Attendance.svc 的本地化字符串。
        /// </summary>
        internal static string IAttendance
        {
            get
            {
                return ResourceManager.GetString("IAttendance", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Company.svc 的本地化字符串。
        /// </summary>
        internal static string ICompany
        {
            get
            {
                return ResourceManager.GetString("ICompany", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Department.svc 的本地化字符串。
        /// </summary>
        internal static string IDepartment
        {
            get
            {
                return ResourceManager.GetString("IDepartment", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Dic.svc 的本地化字符串。
        /// </summary>
        internal static string IDic
        {
            get
            {
                return ResourceManager.GetString("IDic", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 File.svc 的本地化字符串。
        /// </summary>
        internal static string IFile
        {
            get
            {
                return ResourceManager.GetString("IFile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Job.svc 的本地化字符串。
        /// </summary>
        internal static string IJob
        {
            get
            {
                return ResourceManager.GetString("IJob", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Log.svc 的本地化字符串。
        /// </summary>
        internal static string ILog
        {
            get
            {
                return ResourceManager.GetString("ILog", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Menu.svc 的本地化字符串。
        /// </summary>
        internal static string IMenu
        {
            get
            {
                return ResourceManager.GetString("IMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Role.svc 的本地化字符串。
        /// </summary>
        internal static string IRole
        {
            get
            {
                return ResourceManager.GetString("IRole", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Schedule.svc 的本地化字符串。
        /// </summary>
        internal static string ISchedule
        {
            get
            {
                return ResourceManager.GetString("ISchedule", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 UploadFile.svc 的本地化字符串。
        /// </summary>
        internal static string IUploadFile
        {
            get
            {
                return ResourceManager.GetString("IUploadFile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 User.svc 的本地化字符串。
        /// </summary>
        internal static string IUser
        {
            get
            {
                return ResourceManager.GetString("IUser", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 8484 的本地化字符串。
        /// </summary>
        internal static string WcfPort
        {
            get
            {
                return ResourceManager.GetString("WcfPort", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 net.tcp 的本地化字符串。
        /// </summary>
        internal static string WcfSchema
        {
            get
            {
                return ResourceManager.GetString("WcfSchema", resourceCulture);
            }
        }
    }
}
